### ISSUE TITLE
Retorno Automático, informando pagamento

### ISSUE THREAD

**Issue by luizjr** [desenvolvefacil/pixwhmcs#1]
Olá, cara muito bom seu Módulo.
Só falta um item para ficar perfeito, o callback, tem alguma forma de saber se o cliente já pagou e informar para o sistema sem ter que fazer isso manualmente?

**Comment by desenvolvefacil** [comment]
Olá, o callback depende do bano fornecer API para captura de retorno. Como não há uma padronização cada banco definiu de maneira diferente.

Neste momento estas notificações são pagas e disponíveis somente em conta jurídica diante contratação do serviço $$$.

**Comment by luizjr** [comment]
> Olá, o callback depende do bano fornecer API para captura de retorno. Como não há uma padronização cada banco definiu de maneira diferente.
> 
> Neste momento estas notificações são pagas e disponíveis somente em conta jurídica diante contratação do serviço $$$.

Já fez algum para o Banco Inter?
O Valor é acessível?

**Comment by desenvolvefacil** [comment]
Que eu saiba o Inter tem uma API somente para contas PJ (não pode ser MEI).

Teria que ver direto com eles sobre quais serviços estão disponível e valores.

https://ajuda.bancointer.com.br/pt-BR/articles/4284883-como-acesso-o-manual-para-integracao-atraves-de-api

https://ajuda.bancointer.com.br/pt-BR/articles/4257003-o-inter-disponibiliza-alguma-api-para-minha-conta-digital-pj

**Comment by caeteweb** [comment]
> Que eu saiba o Inter tem uma API somente para contas PJ (não pode ser MEI).
> 
> Teria que ver direto com eles sobre quais serviços estão disponível e valores.
> 
> https://ajuda.bancointer.com.br/pt-BR/articles/4284883-como-acesso-o-manual-para-integracao-atraves-de-api
> 
> https://ajuda.bancointer.com.br/pt-BR/articles/4257003-o-inter-disponibiliza-alguma-api-para-minha-conta-digital-pj

O Banco inter disponibiliza isso apenas para boleto! Ainda não tem pra pix!

**Comment by desenvolvefacil** [comment]
O PIX era pra ser revolucionário, porém os bancos não cumprem a documentação padrão e nem disponibilizam API de consultas gratuitas e muitos nem paga tem ainda..

**Comment by desenvolvefacil** [comment]
Atualmente estou trabalhando para autenticar os os PIX feitos via NuBank pelo extrato que eles enviam por e-mail. Se alguém tiver interesse em ajudar.

**Comment by caeteweb** [comment]
> Atualmente estou trabalhando para autenticar os os PIX feitos via NuBank pelo extrato que eles enviam por e-mail. Se alguém tiver interesse em ajudar.

Extrato que vocÊ diz é a mensagem informando Você recebeu um pix! ??? Anota meu zap 91 981276699 Diego Fernando

**Comment by caeteweb** [comment]
> Atualmente estou trabalhando para autenticar os os PIX feitos via NuBank pelo extrato que eles enviam por e-mail. Se alguém tiver interesse em ajudar.

Abre um canal no discord

**Comment by desenvolvefacil** [comment]
Modulo com retorno automatico, reembolso e com QrCode Atualizado em tempo real em:

[https://github.com/desenvolvefacil/dfpixmercadopagowhmcsbrasil](https://github.com/desenvolvefacil/dfpixmercadopagowhmcsbrasil)
