### ISSUE TITLE
QR CODE no email

### ISSUE THREAD

**Issue by caeteweb** [desenvolvefacil/pixwhmcs#2]
Olá existe uma forma de enviar o qrcode como imagem no email da fatura?

**Comment by desenvolvefacil** [comment]
Para enviar Código PIX por email basta colar o código abaixo nos modelos de e-mail

{if $invoice_payment_method=="DF Pix"}{$invoice_payment_link}{/if}

**Comment by desenvolvefacil** [comment]
Eu dei uma mexida no código pra ver se te ajudo:

Atualiza o plug-in e utilize o seguinte código para gerar a imagem do QrCode

```
{$whmcs_url}/modules/gateways/dfpix/gerar_qr_parametros.php?amount={$invoice_total}&chavePix=CHAVEPIX&nome=NOME&cidade=CIDADE&prefixo=PREFIXO&invoiceid={$invoice_id}
```

ou já com a Tag img 

```
<img src="{$whmcs_url}/modules/gateways/dfpix/gerar_qr_parametros.php?amount={$invoice_total}&chavePix=CHAVEPIX&nome=NOME&cidade=CIDADE&prefixo=PREFIXO&invoiceid={$invoice_id}" alt="Fatura #{$invoice_id}" />
```

**1 - Lembre-se de substituir os parâmetros CHAVEPIX, NOME, CIDADE, PREFIXO na url com seus dados**

**2 - O ideal seria fazer uma chamada por API, passando key e token, mas creio que para o que tu necessita o link já deve resolver seu caso.**

Neste caso não tem como um cliente saber a fatura do outro, já que os parâmetros são passados por url.
