### ISSUE TITLE
Página com os dados do pix

### ISSUE THREAD

**Issue by caeteweb** [desenvolvefacil/pixwhmcs#3]
Olá, seria possível uma pagina do tipo: seusite.com.br/whmcs/pix.php?invoiceid=29586&userid=2&mail=teste@gmail.com?

Assim a gente poderia mandar direto o link no email, mesmo se a forma de pagamento do cliente fosse boleto ou outro!

Seria muito bom!
Tentei aqui mas com o pouco conhecimento de programação naõ consegui!
Abs

**Comment by desenvolvefacil** [comment]
Não entendi muito bem. Você quer que o cliente abra diretamente a Fatura?  Se for o caso tem que montar uma página com api para fazer o auto login.

**Comment by caeteweb** [comment]
Não quero que abra diretamente a fatura. 

Gostaria de criar uma página que exibisse o qrcode independentemente do método de pagamento dele.

**Comment by caeteweb** [comment]
> Não quero que abra diretamente a fatura.
> 
> Gostaria de criar uma página que exibisse o qrcode independentemente do método de pagamento dele.

O maior interesse eh oferecer o pix para aqueles que já tem outra forma de pagamento. Mas de forma direta sem ter que entrar na fatura e selecionar a forma de pagamento. 

Já faço isso com boleto do paghiper.  Mando o link direto pro cliente

**Comment by desenvolvefacil** [comment]
Entendi, daria pra fazer uma programação personalizada a parte para gerar o Codigo Pix, QrCode.

Ficaria algo assim:

seusite.com.br/QrCodePix/fat=NumeroFatura

Onde tu pegaria o número da fatura e retornaria a imagem pix.

**Comment by caeteweb** [comment]
> Entendi, daria pra fazer uma programação personalizada a parte para gerar o Codigo Pix, QrCode.
> 
> Ficaria algo assim:
> 
> seusite.com.br/QrCodePix/fat=NumeroFatura
> 
> Onde tu pegaria o número da fatura e retornaria a imagem pix.

Exatamente. Qual seria o melhor caminho pra fazer isso? 
seria bom também incluir o e-mail do cliente junto ao I’d da fatura pra evitar curiosos

**Comment by desenvolvefacil** [comment]
Eu dei uma mexida no código pra ver se te ajudo:

Atualiza o plug-in e utilize o seguinte código para gerar a imagem do QrCode

```
{$whmcs_url}/modules/gateways/dfpix/gerar_qr_parametros.php?amount={$invoice_total}&chavePix=CHAVEPIX&nome=NOME&cidade=CIDADE&prefixo=PREFIXO&invoiceid={$invoice_id}
```

ou já com a Tag img 

```
<img src="{$whmcs_url}/modules/gateways/dfpix/gerar_qr_parametros.php?amount={$invoice_total}&chavePix=CHAVEPIX&nome=NOME&cidade=CIDADE&prefixo=PREFIXO&invoiceid={$invoice_id}" alt="Fatura #{$invoice_id}" />
```

**1 - Lembre-se de substituir os parâmetros CHAVEPIX, NOME, CIDADE, PREFIXO na url com seus dados**

**2 - O ideal seria fazer uma chamada por API, passando key e token, mas creio que para o que tu necessita o link já deve resolver seu caso.**

Neste caso não tem como um cliente saber a fatura do outro, já que os parâmetros são passados por url.

**Comment by caeteweb** [comment]
Show de bola! Eu havia conseguido ajustar mas nesse caso ficou melhor! A propósito, com o pix no PayPal, consegui dar baixa automática, pois o paypal envia a descrição no email. Apenas alguns bancos, como o nubank, não envia a descrição pro paypal. Aparentemente ele substitui a descrição gerada no qrcode por uma em branco. Nesse caso abre um ticket pra equipe dar baixa manualmente.
Muito obrigado!!!

**Comment by desenvolvefacil** [comment]
No caso do PIX do Paypal ele processa o retorno pelo modulo do próprio PayPal. Ele pega pelo InvoiceID.

**Comment by caeteweb** [comment]
> No caso do PIX do Paypal ele processa o retorno pelo modulo do próprio PayPal. Ele pega pelo InvoiceID.

Isso foi pergunta?
Se sim. Eu leio o e-mail que o PayPal manda ao receber um pix. Trato ele e via api adiciono uma transação com os dados no whmcs. A baixa ocorre em alguns segundos. E totalmente grátis.

**Comment by desenvolvefacil** [comment]
Só disse que se o Plugin do Paypal estiver ativo e corretamente configurado, ele consegue tratar este retorno.

**Comment by caeteweb** [comment]
> Só disse que se o Plugin do Paypal estiver ativo e corretamente configurado, ele consegue tratar este retorno.

O pay pal tem módulo pix?
